# Generated by Django 6.0.3 on 2026-03-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='country',
            field=models.CharField(default='India', max_length=100),
            preserve_default=False,
        ),
    ]
