# Generated by Django 6.0.3 on 2026-03-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
